// AUTO-GENERATED by contract/deploy.ts on 2026-09-14T15:19:21.834Z.
// Deployment of the mstocks trading contract.

export const TRADING_CONTRACT_ADDRESS = 'f6801a4d93e41adc3f1b6851f7b55fdb524faae5ee8919d16d45fea3dbf28bed';
export const TRADING_NETWORK = 'preview';
export const TRADING_PRIVATE_STATE_ID = 'tradingPrivateState';

export const TRADING_DEPLOYMENT = {
  "contractName": "Trading",
  "contractAddress": "f6801a4d93e41adc3f1b6851f7b55fdb524faae5ee8919d16d45fea3dbf28bed",
  "privateStateId": "tradingPrivateState",
  "network": "preview",
  "deployedAt": "2026-09-14T15:19:21.834Z",
  "deployTxId": "f0b8d0bb1e4b6e7f5351d1bde6c334280730685284edba3ac2fb980d65022eab",
  "blockHeight": 863570,
  "circuits": [
    "verifyWallet",
    "claimFaucet",
    "depositCash",
    "mintTestStock",
    "placeOrder",
    "cancelOrder",
    "executeTrade"
  ],
  "versions": {
    "compactCompiler": "0.31.1",
    "language": "0.23.0",
    "compactRuntime": "0.16.0",
    "midnightJs": "4.1.1",
    "walletSdk": "1.2.0"
  },
  "endpoints": {
    "indexer": "https://indexer.preview.midnight.network/api/v4/graphql",
    "indexerWS": "wss://indexer.preview.midnight.network/api/v4/graphql/ws",
    "node": "https://rpc.preview.midnight.network",
    "proofServer": "https://proof-server.preview.midnight.network"
  }
} as const;

export const TRADING_INDEXER_URL = 'https://indexer.preview.midnight.network/api/v4/graphql';
export const TRADING_INDEXER_WS = 'wss://indexer.preview.midnight.network/api/v4/graphql/ws';
export const TRADING_NODE_URL = 'https://rpc.preview.midnight.network';
export const TRADING_PROOF_SERVER_URL = 'https://proof-server.preview.midnight.network';

// Testnet faucet (for funding player wallets — the deployer is already funded):
export const TRADING_FAUCET_URL = 'https://midnight-tmnight-preview.nethermind.dev/';
